### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by aliminurudeen** [alfredobarron/smoke#123]
Please how  do I change the default error message to my own error message

**Comment by saranyu-phimsahwan** [comment]
![image](https://user-images.githubusercontent.com/23522561/35275399-342ca854-0072-11e8-8a6f-50dfeb6b5c6a.png)

**Comment by saranyu-phimsahwan** [comment]
![image](https://user-images.githubusercontent.com/23522561/35275429-4f03e0a2-0072-11e8-8db8-b7774e843141.png)

**Comment by aliminurudeen** [comment]
Thanks for the answer, it works like a charm

**Comment by aliminurudeen** [comment]
Thanks for the answer @fangfluke1234  it works like a charm
