### ISSUE TITLE
change license to LGPL

### ISSUE THREAD

**Issue by gochev** [alfredobarron/smoke#47]
I would like to change the license since GPL 3.0 requires everything that uses Smoke to be under GPL 3.0 . LGPL is more suitable for libraries.

**Comment by mostrosonido** [comment]
hi gochev, you´re right we are talking about libraries so, it has to be LGPL, thanks for the help !!

**Comment by mostrosonido** [comment]
You know, the problem with the LGPL it´s that the code can be used in proprietary programs, and we like to preserve the code with the four freedoms. But it´s open to discuss.

**Comment by alfredobarron** [comment]
Update license LGPL, thanks @gochev and @mostrosonido
