### ISSUE TITLE
Looks fantastic?  Any plans for an Angular directive?

### ISSUE THREAD

**Issue by yaronguez** [alfredobarron/smoke#52]
Great job on this plugin!  Do you have any plans to create an Angular port of this where the functionality could be encapsulated into a set of directives?  Has anyone tried using this with Angular as is to see if there are any compatibility issues?

**Comment by mostrosonido** [comment]
Well, the documentation it´s made in Angular. except by two functions that fail (smkFullscreen & smkPanelbut) but we fix it encapsulating the functions https://github.com/alfredobarron/smoke/blob/master/docs/js/scripts.js

**Comment by yaronguez** [comment]
Good to know!
