### ISSUE TITLE
DOes this work with form-horizontal ?

### ISSUE THREAD

**Issue by clarkedesign** [alfredobarron/smoke#60]
I'm using the following code

    <div class="form-group">
     <label for="pdf-name" class="col-sm-3 control-label">Full Name</label>
     <div class="col-sm-9">
      <input required type="text" class="form-control" id="pdf-name" placeholder="Your full name">
     </div>
    </div> 

All works fine apart from the appearance of the warning messages.
They appear as a tooltip below the input field, rather than as in your demos, by changing the colour of the input field and adding a coloured message beneath ?

Any thoughts on this please...

**Comment by alfredobarron** [comment]
update version 2.2.0 

work with form-horizontal

example:
http://codepen.io/alfredobarron/pen/wrfCI

**Comment by clarkedesign** [comment]
Perfect – thank you – great work

[CD Logo 6 - 200px]


Thank you
Sean Clarke · Clarke Design · Helping your business untangle the web
Email:    web@clarkedesign.co.uk<mailto:web@clarkedesign.co.uk>
Web:     www.clarkedesign.co.uk<http://www.clarkedesign.co.uk/>
Tel:         0845 00 94 933 or 01270 761331



Clarke Website Design Ltd is registered in England and Wales under company number 07324906 and our registered office is at 9 Ossmere Close, Sandbach, Cheshire CW11 1FB

Clarke Design is a trading name of Clarke Website Design Ltd. Clarke Design operates under the Clarke Website Design Ltd Terms and Conditions<http://www.clarkedesign.co.uk/terms.asp>

All email communications are private and confidential to the intended addressee. If you believe you have received this email in error please delete it and inform our office at: web@clarkedesign.co.uk<mailto:web@clarkedesign.co.uk>

**Comment by alfredobarron** [comment]
you welcome
