### ISSUE TITLE
smokeCustomizeText ignores the last part of given text

### ISSUE THREAD

**Issue by hidesuke** [alfredobarron/smoke#70]
Hi.

I found bug on smokeCustomizeText.

See the example below

```javascript
$.smokeCustomizeText('some {@} text {@} here', [1, 2]);
```

it returns `some 1 text 2`.  I think correct returned value is `some 1 text 2 here`.

It because, given text is split by `{@}`,  but does not append the last item of split text.

**Comment by alfredobarron** [comment]
Thanks for contributing
