### ISSUE TITLE
Alerts on expanded panel

### ISSUE THREAD

**Issue by radukn** [alfredobarron/smoke#74]
Greetings!

As far as I see, alerts are not showing when a panel is expanded. Any trick to be able to see the alerts? Thank you!

**Comment by alfredobarron** [comment]
An example in codepen or wherever

**Comment by radukn** [comment]
See on your own website.

Open "Info permanent".
http://alfredobarron.github.io/smoke/#/notifications

Change to the panel demo and expand it.
http://alfredobarron.github.io/smoke/#/panel

You will not see the notification. It's not above the expanded panel, but behind (I guess).

Great tool this Smoke.

**Comment by alfredobarron** [comment]
I understand the problem, thanks for the contributed, try to solve it immediately

**Comment by adaniello** [comment]
Hi, why not change simple z-index of .smk-alert-content to a new value bigger then .panel-full (e.g. z-index: 10000, because .panel-full has z-index 9999)?
