### ISSUE TITLE
Empty field

### ISSUE THREAD

**Issue by promogest** [alfredobarron/smoke#78]
if i use smk-type="decimal" in a input field it ask always about a decimal value. how can i manage if it is not required?

**Comment by alfredobarron** [comment]
for now all the fields that are validated need to have the required attribute, and is working on this improvement

**Comment by promogest** [comment]
Thanks @alfredobarron

**Comment by adaniello** [comment]
Solved with this pull request https://github.com/alfredobarron/smoke/pull/90

**Comment by alfredobarron** [comment]
Solved version 3
