### ISSUE TITLE
Notification position

### ISSUE THREAD

**Issue by promogest** [alfredobarron/smoke#79]
There is a way to put notification in the center without override the CSS ?

**Comment by alfredobarron** [comment]
not now, we are working in this

**Comment by alfredobarron** [comment]
thanks for your suggestions, are welcome contributions

**Comment by adaniello** [comment]
A possible solution at pull request https://github.com/alfredobarron/smoke/pull/83

**Comment by alfredobarron** [comment]
Solved in version 3
