### ISSUE TITLE
[Feature request] variable position on notifications

### ISSUE THREAD

**Issue by pixotic** [alfredobarron/smoke#81]
Hi there,

Would it be possible to add the ability to dictate where a notification should appear, such as bottom-right, top-left etc?

Thanks.

**Comment by alfredobarron** [comment]
#79 issue

**Comment by pixotic** [comment]
I'm sorry, I didn't notice that this was already on your radar.

**Comment by adaniello** [comment]
A possible solution at pull request https://github.com/alfredobarron/smoke/pull/83
