### ISSUE TITLE
Alert not working

### ISSUE THREAD

**Issue by jsantari** [alfredobarron/smoke#89]
I'm trying to use the following and it doesn't work - it returns undefined and no alert is displayed? I'm using progress bar and that does work? Not sure what's wrong.

$.smkAlert({text:'Select a new Category"', type:'warning'});

**Comment by adaniello** [comment]
Please, send your full code or part, eg via codepen

**Comment by jsantari** [comment]
I've determined that the problem was a conflict with an off canvas plugin (jquery.offcanvas.js) I was trying to use on the page. Removed it due to another problem it was causing with the layout and the alert started working. Thanks.
